????? ???????? ??? ?????? TeamCity

#apiBaseUrl=http://localhost:8111
#apiPath=/api
#apiVersion=/v1/
#admin.username=admin
#admin.password=adminTeamCity
#
#uiRemote=http://localhost:4444/wd/hub
#uiBaseUrl=http://192.168.1.103:3000
#Configuration.browser=chrome
#Configuration.browserSize=1920x1080
#test.environment=stage

teamcity.baseUrl=http://teamcity-server:8111
teamcity.token=<??? access token>
teamcity.nbankBuildTypeId=NBank_Tests